spring:
  datasource:
    url: jdbc:h2:file:~/test3;DB_CLOSE_ON_EXIT=FALSE
    password: password
    username: sa
  jpa:
    database-platform: org.h2.Driver
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true